version: '3'

services:
  all_users:
    image: webdevops/php-apache-dev:8.2-alpine
    container_name: yasmf_all_users_app
    working_dir: /app/
    ports:
      - 8080:80
    volumes:
      - ./:/app/
  all_users_db:
    image: mysql:8
    container_name: all_users_db
    environment:
      - MYSQL_USER=all_users
      - MYSQL_DATABASE=all_users
      - MYSQL_PASSWORD=all_users
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "6612:3306"
    volumes:
      - ./SQL/:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8 --collation-server=utf8_general_ci 